//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wordle.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wordle.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   cigar
        ///rebut
        ///sissy
        ///humph
        ///awake
        ///blush
        ///focal
        ///evade
        ///naval
        ///serve
        ///heath
        ///dwarf
        ///model
        ///karma
        ///stink
        ///grade
        ///quiet
        ///bench
        ///abate
        ///feign
        ///major
        ///death
        ///fresh
        ///crust
        ///stool
        ///colon
        ///abase
        ///marry
        ///react
        ///batty
        ///pride
        ///floss
        ///helix
        ///croak
        ///staff
        ///paper
        ///unfed
        ///whelp
        ///trawl
        ///outdo
        ///adobe
        ///crazy
        ///sower
        ///repay
        ///digit
        ///crate
        ///cluck
        ///spike
        ///mimic
        ///pound
        ///maxim
        ///linen
        ///unmet
        ///flesh
        ///booby
        ///forth
        ///first
        ///stand
        ///belly
        ///ivory
        ///seedy
        ///print
        ///yearn
        ///drain
        ///bribe
        ///stout
        ///panel
        ///crass
        ///flume
        ///offal
        ///agree
        ///error
        ///swirl
        ///a [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string candidates {
            get {
                return ResourceManager.GetString("candidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   aahed
        ///aalii
        ///aargh
        ///aarti
        ///abaca
        ///abaci
        ///abacs
        ///abaft
        ///abaka
        ///abamp
        ///aband
        ///abash
        ///abask
        ///abaya
        ///abbas
        ///abbed
        ///abbes
        ///abcee
        ///abeam
        ///abear
        ///abele
        ///abers
        ///abets
        ///abies
        ///abler
        ///ables
        ///ablet
        ///ablow
        ///abmho
        ///abohm
        ///aboil
        ///aboma
        ///aboon
        ///abord
        ///abore
        ///abram
        ///abray
        ///abrim
        ///abrin
        ///abris
        ///absey
        ///absit
        ///abuna
        ///abune
        ///abuts
        ///abuzz
        ///abyes
        ///abysm
        ///acais
        ///acari
        ///accas
        ///accoy
        ///acerb
        ///acers
        ///aceta
        ///achar
        ///ached
        ///aches
        ///achoo
        ///acids
        ///acidy
        ///acing
        ///acini
        ///ackee
        ///acker
        ///acmes
        ///acmic
        ///acned
        ///acnes
        ///acock
        ///acold
        ///acred
        ///acres
        ///a [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string valids {
            get {
                return ResourceManager.GetString("valids", resourceCulture);
            }
        }
    }
}
